[package]
name = "msrf"
version = "0.0.1"
edition = "2024"

[features]
default = ["reader", "writer"]
reader = []
writer = []

[dev-dependencies]
constcat = "0.6.1"

[workspace]
resolver = "2"
members = [
    "extension",
]
